# Configuración básica del bot

PREFIX: "!"
STATUS: # %minecraft_online%
  - "play.spacmeoon.es"
  - "asdasdasdasga"
SERVER-ID: "817783818886709249"
STATUS-MODE: "ONLINE" # ONLINE | AUSENTE | DND
STATUS-CHANGE-DELAY: 5 # En segundos